#pragma once
#include "ImageCanvas.h"
/**
@file
Subclass of SpriteFormFrame, which is generated by wxFormBuilder.
*/
//// end generated include

#include "SpriteFormBase.h"
#include "MyProjectBase.h"
#include "MainFrame.h"
#include "FileProcessor.h"
class MainFrame;  // Forward declaration of MainFrame

/** Implementing SpriteFormFrame */
class SpriteForm : public SpriteFormFrame {
   protected:
    bool IsBitmapValid(const wxBitmap& bmp) const;
    // Handlers for SpriteFormFrame events.
    IndexCoords GetCoords(int index);
    void LimitCoord(IndexCoords& coord);
    void OnEnterWindow(wxMouseEvent& event);
    void OnLeaveWindow(wxMouseEvent& event);
    void OnMotion(wxMouseEvent& event);
    void OnPaint(wxPaintEvent& event);
    void OnOpen(wxCommandEvent& event);
    void OnXChange(wxSpinEvent& event);
    void OnYChange(wxSpinEvent& event);
    void OnWidthChange(wxSpinEvent& event);
    void OnHeightChange(wxSpinEvent& event);
    void OnCancel(wxCommandEvent& event);
    void OnContinue(wxCommandEvent& event);
    void OnSelectedIndex(wxSpinEvent& event);
    void SetCoords(IndexCoords coord);
    void OnSize(wxSizeEvent& event);
    void UpdateFields();
    void OnGWidth(wxSpinEvent& event);
    void OnGHeight(wxSpinEvent& event);
    void OnRightMDown(wxMouseEvent& event);
    void DisableFields();
    void EnableFields();
    void UpdateReal(bool height = false);
    void OnLeftMDown(wxMouseEvent& event);

   public:
    /** Constructor */
    SpriteForm(wxWindow* parent, wxBitmap& bitmap, DraggableImage* img, MainFrame* mainFrame);
    //// end generated class members
   private:
    wxBitmap        zoomedPreview = wxBitmap(128, 128);
    wxPoint         mousePos;
    wxBitmap&       bitmap;     // Bitmap to display
    DraggableImage* dragImage;  // Image being edited
    MainFrame*      mFrame;     // Pointer to the main frame
    wxSize          realSize;
    int             currentIndex = 0;              // Current index of the image being edited
    bool            isDragging   = false;          // Flag to check if dragging is in progress
    wxPoint         offset       = wxPoint(0, 0);  // Offset for the bitmap position
    bool            inWindow     = false;
    wxPoint         selectionStartPos;  // Start position of selection
    wxSize          selectionSize;      // Size of the selection rectangle
    wxPoint         dragStartPos;       // Position where dragging started
    float           ratio = 1.0f;       // Ratio for scaling the bitmap
};
